title: '~'
url: "https://alge.rs"
markdown: CommonMarkGhPages
remote_theme: b2a3e8/jekyll-theme-console
style: hacker
# header_pages:
#   - 'index.md'
google_analytics: G-R3MLS3YS29
# footer: '<a href="https://github.com/algers>/github</a>'