# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Markdown Metrics
on:
  # Schedule updates (each hour)
  schedule: [{ cron: '0 * * * *' }]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: algers
          template: classic
          filename: METRICS.md
          base: header, activity, community, repositories
          config_timezone: America/Chicago
          plugin_gists: yes
          plugin_habits: yes
          plugin_habits_days: 360
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_introduction: yes
          plugin_introduction_title: no
          plugin_lines: yes
          plugin_stars: yes
          plugin_stars_limit: 3
          plugin_topics: yes
          plugin_topics_sort: stars # Sort by most starred topics
          plugin_topics_mode: mastered # Display icons instead of labels
          plugin_topics_limit: 0 # Disable limitations
          plugin_music: yes
          plugin_music_provider: spotify # Use Spotify as provider
          plugin_music_mode: recent # Set plugin mode
          plugin_music_limit: 4 # Limit to 4 entries
          plugin_music_played_at: yes # Show timestamp (for spotify only)
          plugin_music_token: '${{ secrets.SPOTIFY_CLIENT_ID }}, ${{ secrets.SPOTIFY_CLIENT_SECRET }}, ${{ secrets.SPOTIFY_REFRESH_TOKEN }}'
